# Generated by Django 4.1.2 on 2022-10-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbrand',
            name='comments',
            field=models.TextField(max_length=200, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='addbrand',
            name='engine',
            field=models.TextField(verbose_name='Двигатель'),
        ),
        migrations.AlterField(
            model_name='addbrand',
            name='hp',
            field=models.CharField(max_length=200, verbose_name='Лошадиные силы'),
        ),
        migrations.AlterField(
            model_name='addbrand',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='addbrand',
            name='nm',
            field=models.CharField(max_length=200, verbose_name='Ньютон метр'),
        ),
        migrations.AlterField(
            model_name='addbrand',
            name='series',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='model',
            name='engine',
            field=models.TextField(null=True, verbose_name='Двигатель'),
        ),
        migrations.AlterField(
            model_name='model',
            name='series',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='modelcomment',
            name='text',
            field=models.TextField(),
        ),
    ]
