# Generated by Django 4.1.2 on 2022-10-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_addbrand_comments_alter_addbrand_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='hp',
            field=models.IntegerField(null=True, verbose_name='Лошадиные силы'),
        ),
        migrations.AlterField(
            model_name='model',
            name='nm',
            field=models.IntegerField(null=True, verbose_name='Ньютон метр'),
        ),
    ]
